# Generated by Django 5.0.14 on 2026-06-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileAppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("pin_hash", models.CharField(max_length=255)),
                (
                    "network",
                    models.CharField(
                        choices=[("MTN", "MTN"), ("ORANGE", "ORANGE")], max_length=20
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fcm_token", models.CharField(blank=True, max_length=500, null=True)),
                ("fcm_token_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mobile_app_users",
            },
        ),
        migrations.CreateModel(
            name="CryptoWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("BTC", "BTC"), ("ETH", "ETH"), ("USDT", "USDT")],
                        max_length=10,
                    ),
                ),
                ("testnet_address", models.CharField(max_length=100, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("bitcoin_testnet", "bitcoin_testnet"),
                            ("sepolia", "sepolia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_wallets",
                        to="paycam_mobile_app.mobileappuser",
                    ),
                ),
            ],
            options={
                "db_table": "crypto_wallets",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.CharField(max_length=20)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="paycam_mobile_app.mobileappuser",
                    ),
                ),
            ],
            options={
                "db_table": "wallets",
            },
        ),
    ]
