# Generated by Django 5.0.14 on 2026-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paycam_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="environment",
            field=models.CharField(choices=[("live", "live")], max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
