# Generated by Django 5.0.14 on 2026-07-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paycam_auth", "0002_alter_apikey_environment_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="default_webhook_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
