# Generated by Django 5.0.14 on 2026-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paycam_auth", "0003_user_business_name_user_default_webhook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
    ]
