# Generated by Django 5.0.14 on 2026-06-18 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paycam_auth", "0001_initial"),
        ("paycam_mobile_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(max_length=10)),
                ("to_currency", models.CharField(max_length=10)),
                ("rate", models.DecimalField(decimal_places=10, max_digits=20)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "exchange_rates",
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "-fetched_at"],
                        name="exchange_ra_from_cu_d4a4c2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XAF", "XAF"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("NGN", "NGN"),
                            ("GHS", "GHS"),
                            ("KES", "KES"),
                            ("ETH", "ETH"),
                            ("BTC", "BTC"),
                            ("USDT", "USDT"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("network", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mtn_momo", "mtn_momo"),
                            ("orange_money", "orange_money"),
                            ("card", "card"),
                            ("crypto_btc", "crypto_btc"),
                            ("crypto_eth", "crypto_eth"),
                            ("crypto_usdt", "crypto_usdt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("expired", "expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "crypto_wallet_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "crypto_tx_hash",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "webhook_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "redirect_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paycam_auth.apikey",
                    ),
                ),
                (
                    "customer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paycam_mobile_app.mobileappuser",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
