# Generated by Django 5.0.14 on 2026-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paycam_payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="crypto_confirm_start_block",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
