# Generated by Django 5.0.14 on 2026-07-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycam_payments', '0002_transaction_crypto_confirm_start_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
